"""
backend/tests/services/test_adversarial_m1.py

Adversarial Stress Test Suite for Milestone 1:
1. Corner Trap Elimination at 1.414r:
   Coordinates at bounding box corners (geodesic distance ~ 1.414 r) MUST be fetched
   by SQL pre-filter (BETWEEN) but STRICTLY EXCLUDED by spherical Haversine post-filter.
   Tested for BOTH OpenAQ ground stations and NASA FIRMS active fire hotspots.
2. Tangent Boundary Precision:
   Points at (r - 10 meters) MUST be included.
   Points at (r + 10 meters) MUST be excluded.
   Tested across cardinal and diagonal bearings.
3. DQS Distance Decay:
   Exact mathematical decay at d = 0 km (1.0), 10 km (0.82), 25 km (0.55), 50 km (0.10), 75 km (0.10).
   Dynamic station measurement DQS recomputation.
4. FCS Dispersion Penalty:
   - Single sensor (dispersion = 0, penalty = 1.0)
   - Multiple identical sensors (dispersion = 0, penalty = 1.0)
   - Dispersed sensors (sigma / mu in (0, 1), proportional penalty)
   - Highly dispersed sensors (sigma / mu >= 1.0 -> FCS = 0.0)
   - Zero-mean edge cases ([0.0, 0.0] -> penalty 1.0; [-10, 10] -> penalty 0.0)
   - Robustness to NaN, inf, corrupt inputs
5. Sensor Combination Matrix:
   - Only ground sensors
   - Only active fires
   - Both ground sensors and fires
   - Neither (Zero-Fake-Data empty state)
"""

from datetime import datetime, timedelta, timezone
import math
import pytest
import pytest_asyncio

from db.database import DatabaseManager
from services.facility_intelligence import (
    EARTH_RADIUS_KM,
    FacilityIntelligenceService,
    haversine_distance,
)
from core.quality import (
    calculate_dqs,
    calculate_fcs,
    calculate_spatial_representativeness,
    get_dqs_breakdown,
    get_fcs_confidence_level,
)


# =============================================================================
# Helper: Geodesic destination point given start, bearing (deg), and distance (km)
# =============================================================================
def destination_point(lat: float, lon: float, distance_km: float, bearing_deg: float):
    """Calculate destination coordinate using great-circle direct problem."""
    d_div_r = distance_km / EARTH_RADIUS_KM
    theta = math.radians(bearing_deg)
    phi1 = math.radians(lat)
    lambda1 = math.radians(lon)

    sin_phi2 = math.sin(phi1) * math.cos(d_div_r) + math.cos(phi1) * math.sin(d_div_r) * math.cos(theta)
    phi2 = math.asin(max(-1.0, min(1.0, sin_phi2)))
    y = math.sin(theta) * math.sin(d_div_r) * math.cos(phi1)
    x = math.cos(d_div_r) - math.sin(phi1) * math.sin(phi2)
    lambda2 = lambda1 + math.atan2(y, x)

    return math.degrees(phi2), (math.degrees(lambda2) + 540.0) % 360.0 - 180.0


# =============================================================================
# 1. Adversarial Corner Trap Elimination (1.414r) & Tangent Boundary Tests
# =============================================================================

@pytest_asyncio.fixture
async def spatial_adversarial_db():
    """
    In-memory DB specifically populated with adversarial spatial traps around
    Facility 201 at (lat=28.5000, lon=77.2000), radius = 10.0 km.
    """
    db = DatabaseManager()
    await db.initialize(":memory:")

    fac_lat = 28.5000
    fac_lon = 77.2000
    r_km = 10.0

    # Facility
    await db.execute(
        """INSERT INTO industries (id, name, type, latitude, longitude, state, capacity)
           VALUES (?, ?, ?, ?, ?, ?, ?)""",
        (201, "Stress Test Plant Alpha", "Power", fac_lat, fac_lon, "Delhi", "100 MW"),
    )

    # Calculate bounding box bounds as generated by service
    service = FacilityIntelligenceService(db)
    bbox = service.generate_bounding_box(fac_lat, fac_lon, r_km)
    min_lat, max_lat = bbox["min_lat"], bbox["max_lat"]
    min_lon, max_lon = bbox["min_lon"], bbox["max_lon"]

    # --- 1. Corner Traps (at 4 exact corners of the SQL bounding box) ---
    # In degree space, these are exactly on the SQL bounding box boundary.
    # Geodesic distance is ~ 14.16 km > 10.0 km (approx sqrt(2) * r = 1.414 r).
    corners = {
        "corner_ne": (max_lat, max_lon),
        "corner_nw": (max_lat, min_lon),
        "corner_se": (min_lat, max_lon),
        "corner_sw": (min_lat, min_lon),
    }

    now_iso = datetime.now(timezone.utc).isoformat()
    today_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    # Insert corner stations and corner fires
    fire_id = 100
    for name, (c_lat, c_lon) in corners.items():
        st_id = f"st_{name}"
        await db.execute(
            """INSERT INTO openaq_stations (station_id, name, latitude, longitude, city, country, last_updated, parameters)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?)""",
            (st_id, f"OpenAQ {name}", c_lat, c_lon, "Delhi", "IN", now_iso, "pm25"),
        )
        await db.execute(
            """INSERT INTO openaq_measurements (station_id, parameter, value, unit, timestamp, dqs)
               VALUES (?, ?, ?, ?, ?, ?)""",
            (st_id, "pm25", 55.0, "ug/m3", now_iso, 0.8),
        )

        fire_id += 1
        await db.execute(
            """INSERT INTO nasa_firms_fires (id, latitude, longitude, brightness, scan, track, acq_date, acq_time, satellite, confidence, frp, dqs)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
            (fire_id, c_lat, c_lon, 340.0, 1.0, 1.0, today_str, "1200", "VIIRS", "nominal", 10.0, 0.75),
        )

    # --- 2. Tangent Boundaries (r - 10m vs r + 10m) ---
    # r = 10.0 km -> r - 10m = 9.990 km, r + 10m = 10.010 km
    # Test across 4 cardinal and 4 diagonal bearings: 0 (N), 45 (NE), 90 (E), 180 (S), 270 (W)
    bearings = [0.0, 45.0, 90.0, 180.0, 225.0, 270.0]
    for b in bearings:
        # Inner point at r - 10m (9.990 km) -> MUST BE INCLUDED
        in_lat, in_lon = destination_point(fac_lat, fac_lon, distance_km=9.990, bearing_deg=b)
        st_in_id = f"st_in_{int(b)}"
        await db.execute(
            """INSERT INTO openaq_stations (station_id, name, latitude, longitude, city, country, last_updated, parameters)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?)""",
            (st_in_id, f"OpenAQ Inner {int(b)}", in_lat, in_lon, "Delhi", "IN", now_iso, "pm25"),
        )
        await db.execute(
            """INSERT INTO openaq_measurements (station_id, parameter, value, unit, timestamp, dqs)
               VALUES (?, ?, ?, ?, ?, ?)""",
            (st_in_id, "pm25", 60.0, "ug/m3", now_iso, 0.8),
        )

        fire_id += 1
        await db.execute(
            """INSERT INTO nasa_firms_fires (id, latitude, longitude, brightness, scan, track, acq_date, acq_time, satellite, confidence, frp, dqs)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
            (fire_id, in_lat, in_lon, 350.0, 1.0, 1.0, today_str, "1200", "VIIRS", "nominal", 15.0, 0.75),
        )

        # Outer point at r + 10m (10.010 km) -> MUST BE EXCLUDED
        out_lat, out_lon = destination_point(fac_lat, fac_lon, distance_km=10.010, bearing_deg=b)
        st_out_id = f"st_out_{int(b)}"
        await db.execute(
            """INSERT INTO openaq_stations (station_id, name, latitude, longitude, city, country, last_updated, parameters)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?)""",
            (st_out_id, f"OpenAQ Outer {int(b)}", out_lat, out_lon, "Delhi", "IN", now_iso, "pm25"),
        )
        await db.execute(
            """INSERT INTO openaq_measurements (station_id, parameter, value, unit, timestamp, dqs)
               VALUES (?, ?, ?, ?, ?, ?)""",
            (st_out_id, "pm25", 60.0, "ug/m3", now_iso, 0.8),
        )

        fire_id += 1
        await db.execute(
            """INSERT INTO nasa_firms_fires (id, latitude, longitude, brightness, scan, track, acq_date, acq_time, satellite, confidence, frp, dqs)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
            (fire_id, out_lat, out_lon, 350.0, 1.0, 1.0, today_str, "1200", "VIIRS", "nominal", 15.0, 0.75),
        )

    yield db
    await db.close()


@pytest.mark.asyncio
async def test_adversarial_corner_traps_strictly_excluded(spatial_adversarial_db):
    """
    ADVERSARIAL CHALLENGE 1: Corner Trap Elimination at 1.414r.
    Verifies that all 4 corners of the SQL bounding box (at ~1.414r = ~14.16 km)
    are returned by SQL BETWEEN pre-filter, but strictly eliminated by Haversine post-filter.
    """
    service = FacilityIntelligenceService(spatial_adversarial_db)
    fac_lat, fac_lon = 28.5000, 77.2000
    radius_km = 10.0

    # 1. OpenAQ Stations:
    stations = await service.get_openaq_stations_within_radius(fac_lat, fac_lon, radius_km=radius_km)
    found_st_ids = {s["station_id"] for s in stations}

    for corner in ("corner_ne", "corner_nw", "corner_se", "corner_sw"):
        corner_st_id = f"st_{corner}"
        assert corner_st_id not in found_st_ids, (
            f"CORNER TRAP FAILED: Station {corner_st_id} at ~1.414r was NOT eliminated by Haversine filter!"
        )

    # 2. NASA FIRMS Fires:
    fires = await service.get_firms_fires_within_radius(fac_lat, fac_lon, radius_km=radius_km)
    found_fire_ids = {f["id"] for f in fires}

    for corner_fire_id in (101, 102, 103, 104):
        assert corner_fire_id not in found_fire_ids, (
            f"CORNER TRAP FAILED: Fire {corner_fire_id} at ~1.414r was NOT eliminated by Haversine filter!"
        )


@pytest.mark.asyncio
async def test_adversarial_tangent_boundary_inclusion_and_exclusion(spatial_adversarial_db):
    """
    ADVERSARIAL CHALLENGE 2: Tangent Boundary Precision.
    Verifies:
    - Points at (r - 10m) = 9.990 km are strictly INCLUDED.
    - Points at (r + 10m) = 10.010 km are strictly EXCLUDED.
    """
    service = FacilityIntelligenceService(spatial_adversarial_db)
    fac_lat, fac_lon = 28.5000, 77.2000
    radius_km = 10.0

    stations = await service.get_openaq_stations_within_radius(fac_lat, fac_lon, radius_km=radius_km)
    st_ids = {s["station_id"] for s in stations}

    fires = await service.get_firms_fires_within_radius(fac_lat, fac_lon, radius_km=radius_km)
    fire_dists = {f["id"]: f["distance_km"] for f in fires}

    bearings = [0, 45, 90, 180, 225, 270]
    for b in bearings:
        in_id = f"st_in_{b}"
        out_id = f"st_out_{b}"

        # Inner point must be INCLUDED
        assert in_id in st_ids, f"BOUNDARY FAILED: Station {in_id} at 9.990 km (r - 10m) was falsely excluded!"
        # Outer point must be EXCLUDED
        assert out_id not in st_ids, f"BOUNDARY FAILED: Station {out_id} at 10.010 km (r + 10m) was falsely included!"

    # All returned stations must have distance <= 10.0 km
    for s in stations:
        assert s["distance_km"] <= radius_km, f"Station {s['station_id']} distance {s['distance_km']} > {radius_km}"

    # All returned fires must have distance <= 10.0 km
    for f in fires:
        assert f["distance_km"] <= radius_km, f"Fire {f['id']} distance {f['distance_km']} > {radius_km}"


# =============================================================================
# 2. DQS Distance Decay & Sub-indices Stress Tests
# =============================================================================

def test_dqs_spatial_distance_decay_benchmarks():
    """
    ADVERSARIAL CHALLENGE 3: Verify exact DQS distance decay formula:
    Q_spatial = max(0.1, 1.0 - 0.9 * (d / 50.0))
    Benchmarks:
    - 0 km -> 1.000000
    - 10 km -> 0.820000
    - 25 km -> 0.550000
    - 50 km -> 0.100000
    - 75 km -> 0.100000 (floor clamped)
    """
    assert calculate_spatial_representativeness(0.0) == pytest.approx(1.000000, abs=1e-5)
    assert calculate_spatial_representativeness(10.0) == pytest.approx(0.820000, abs=1e-5)
    assert calculate_spatial_representativeness(25.0) == pytest.approx(0.550000, abs=1e-5)
    assert calculate_spatial_representativeness(50.0) == pytest.approx(0.100000, abs=1e-5)
    assert calculate_spatial_representativeness(75.0) == pytest.approx(0.100000, abs=1e-5)
    assert calculate_spatial_representativeness(100.0) == pytest.approx(0.100000, abs=1e-5)

    # Non-finite and negative inputs
    assert calculate_spatial_representativeness(-5.0) == pytest.approx(1.000000, abs=1e-5)
    assert calculate_spatial_representativeness(float("nan")) == 0.1
    assert calculate_spatial_representativeness(float("inf")) == 0.1

    # End-to-end calculate_dqs at benchmark distances for fresh, reference, valid data
    now_ts = datetime.now(timezone.utc).isoformat()
    dqs_0 = calculate_dqs(50.0, "pm25", now_ts, distance_km=0.0, sensor_type="reference")
    assert dqs_0 == pytest.approx(1.000000, abs=1e-4)

    dqs_25 = calculate_dqs(50.0, "pm25", now_ts, distance_km=25.0, sensor_type="reference")
    assert dqs_25 == pytest.approx(0.550000, abs=1e-4)

    dqs_50 = calculate_dqs(50.0, "pm25", now_ts, distance_km=50.0, sensor_type="reference")
    assert dqs_50 == pytest.approx(0.100000, abs=1e-4)


@pytest.mark.asyncio
async def test_dynamic_measurement_dqs_decay_in_service():
    """
    Verifies that get_latest_measurements_for_stations computes distance decay
    reflecting each station's actual distance from the facility.
    """
    db = DatabaseManager()
    await db.initialize(":memory:")

    now_iso = datetime.now(timezone.utc).isoformat()
    stations = [
        {"station_id": "st_0km", "distance_km": 0.0, "latitude": 28.5, "longitude": 77.2},
        {"station_id": "st_25km", "distance_km": 25.0, "latitude": 28.7, "longitude": 77.2},
        {"station_id": "st_50km", "distance_km": 50.0, "latitude": 28.9, "longitude": 77.2},
    ]

    for st in stations:
        await db.execute(
            """INSERT INTO openaq_measurements (station_id, parameter, value, unit, timestamp, dqs)
               VALUES (?, ?, ?, ?, ?, ?)""",
            (st["station_id"], "pm25", 50.0, "ug/m3", now_iso, 0.5),
        )

    service = FacilityIntelligenceService(db)
    detailed = await service.get_latest_measurements_for_stations(stations)

    by_id = {s["station_id"]: s for s in detailed}

    # Station at 0 km
    p_0 = by_id["st_0km"]["parameters"]["pm25"]
    assert p_0["dqs_breakdown"]["spatial"] == pytest.approx(1.0, abs=1e-4)
    assert p_0["dqs"] == pytest.approx(1.0, abs=1e-4)

    # Station at 25 km
    p_25 = by_id["st_25km"]["parameters"]["pm25"]
    assert p_25["dqs_breakdown"]["spatial"] == pytest.approx(0.55, abs=1e-4)
    assert p_25["dqs"] == pytest.approx(0.55, abs=1e-4)

    # Station at 50 km
    p_50 = by_id["st_50km"]["parameters"]["pm25"]
    assert p_50["dqs_breakdown"]["spatial"] == pytest.approx(0.10, abs=1e-4)
    assert p_50["dqs"] == pytest.approx(0.10, abs=1e-4)

    await db.close()


# =============================================================================
# 3. FCS Dispersion Penalty Stress Tests
# =============================================================================

def test_fcs_dispersion_penalty_spectrum():
    """
    ADVERSARIAL CHALLENGE 4: FCS Mathematical Properties.
    Formula: FCS = (sum(DQS_i * w_i) / sum(w_i)) * max(0.0, 1.0 - sigma / mu)
    """
    # 1. Single sensor: dispersion is 0, penalty is 1.0
    assert calculate_fcs([0.85], [45.0]) == pytest.approx(0.85, abs=1e-4)
    assert calculate_fcs([0.50], [100.0]) == pytest.approx(0.50, abs=1e-4)
    assert calculate_fcs([0.0], [50.0]) == 0.0

    # 2. Identical observations: sigma = 0, penalty = 1.0
    fcs_identical = calculate_fcs([0.8, 0.9, 0.7], [60.0, 60.0, 60.0])
    assert fcs_identical == pytest.approx(0.800000, abs=1e-4)

    # 3. Mild dispersion: mu = 50, values = [45, 55], sigma = 5, ratio = 0.10 -> penalty 0.90
    fcs_mild = calculate_fcs([0.9, 0.9], [45.0, 55.0])
    assert fcs_mild == pytest.approx(0.9 * 0.90, abs=1e-4)

    # 4. Severe dispersion (sigma / mu == 1.0): values [0, 100], mu = 50, sigma = 50 -> ratio = 1.0 -> FCS = 0.0
    fcs_severe_1 = calculate_fcs([0.95, 0.95], [0.0, 100.0])
    assert fcs_severe_1 == 0.0

    # 5. Extreme dispersion (sigma / mu > 1.0): values [1, 1, 500] -> FCS = 0.0
    fcs_severe_2 = calculate_fcs([0.9, 0.9, 0.9], [1.0, 1.0, 500.0])
    assert fcs_severe_2 == 0.0

    # 6. Zero mean edge cases:
    # All zero: penalty = 1.0
    assert calculate_fcs([0.8, 0.8], [0.0, 0.0]) == pytest.approx(0.8, abs=1e-4)
    # Cancelling non-zero: mu = 0 but values != 0 -> penalty = 0.0
    assert calculate_fcs([0.8, 0.8], [-10.0, 10.0]) == 0.0

    # 7. Confidence tiers mapping
    assert get_fcs_confidence_level(0.85) == "HIGH"
    assert get_fcs_confidence_level(0.80) == "MEDIUM"
    assert get_fcs_confidence_level(0.55) == "MEDIUM"
    assert get_fcs_confidence_level(0.50) == "LOW"
    assert get_fcs_confidence_level(0.10) == "LOW"
    assert get_fcs_confidence_level(0.0) == "LOW"

    # 8. Corrupt and adversarial inputs:
    # NaN and inf in values
    assert calculate_fcs([0.8, 0.8], [float("nan"), 50.0]) == 0.0
    assert calculate_fcs([0.8, 0.8], [float("inf"), 50.0]) == 0.0
    # Empty inputs
    assert calculate_fcs([], []) == 0.0
    # Mismatched lengths raise ValueError
    with pytest.raises(ValueError):
        calculate_fcs([0.8], [50.0, 60.0])


# =============================================================================
# 4. Sensor Combination Matrix in FacilityIntelligenceService
# =============================================================================

@pytest_asyncio.fixture
async def combo_matrix_db():
    """Database supporting tests for 4 combinations of sensor presence."""
    db = DatabaseManager()
    await db.initialize(":memory:")

    now_utc = datetime.now(timezone.utc)
    now_iso = now_utc.isoformat()
    today_str = now_utc.strftime("%Y-%m-%d")
    recent_acq_time = (now_utc - timedelta(minutes=15)).strftime("%H%M")

    # Facility 301: Only Ground Sensors (lat=10.0, lon=10.0)
    await db.execute(
        "INSERT INTO industries (id, name, type, latitude, longitude) VALUES (?, ?, ?, ?, ?)",
        (301, "Ground Only Plant", "Power", 10.0, 10.0),
    )
    await db.execute(
        """INSERT INTO openaq_stations (station_id, name, latitude, longitude, city, country, last_updated, parameters)
           VALUES (?, ?, ?, ?, ?, ?, ?, ?)""",
        ("st_301", "Station 301", 10.01, 10.01, "City", "IN", now_iso, "pm25"),
    )
    await db.execute(
        "INSERT INTO openaq_measurements (station_id, parameter, value, unit, timestamp, dqs) VALUES (?, ?, ?, ?, ?, ?)",
        ("st_301", "pm25", 55.0, "ug/m3", now_iso, 0.85),
    )

    # Facility 302: Only Fires (lat=20.0, lon=20.0)
    await db.execute(
        "INSERT INTO industries (id, name, type, latitude, longitude) VALUES (?, ?, ?, ?, ?)",
        (302, "Fires Only Plant", "Power", 20.0, 20.0),
    )
    await db.execute(
        """INSERT INTO nasa_firms_fires (id, latitude, longitude, brightness, scan, track, acq_date, acq_time, satellite, confidence, frp, dqs)
           VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
        (3021, 20.01, 20.01, 340.0, 1.0, 1.0, today_str, recent_acq_time, "VIIRS", "nominal", 10.0, 0.76),
    )

    # Facility 303: Both Ground Sensors and Fires (lat=30.0, lon=30.0)
    await db.execute(
        "INSERT INTO industries (id, name, type, latitude, longitude) VALUES (?, ?, ?, ?, ?)",
        (303, "Both Sensors Plant", "Power", 30.0, 30.0),
    )
    await db.execute(
        """INSERT INTO openaq_stations (station_id, name, latitude, longitude, city, country, last_updated, parameters)
           VALUES (?, ?, ?, ?, ?, ?, ?, ?)""",
        ("st_303", "Station 303", 30.01, 30.01, "City", "IN", now_iso, "pm25"),
    )
    await db.execute(
        "INSERT INTO openaq_measurements (station_id, parameter, value, unit, timestamp, dqs) VALUES (?, ?, ?, ?, ?, ?)",
        ("st_303", "pm25", 75.0, "ug/m3", now_iso, 0.85),
    )
    await db.execute(
        """INSERT INTO nasa_firms_fires (id, latitude, longitude, brightness, scan, track, acq_date, acq_time, satellite, confidence, frp, dqs)
           VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
        (3031, 30.02, 30.02, 360.0, 1.0, 1.0, today_str, recent_acq_time, "VIIRS", "nominal", 20.0, 0.76),
    )

    # Facility 304: Neither (Zero-Fake-Data empty zone) (lat=40.0, lon=40.0)
    await db.execute(
        "INSERT INTO industries (id, name, type, latitude, longitude) VALUES (?, ?, ?, ?, ?)",
        (304, "Empty Zone Plant", "Solar", 40.0, 40.0),
    )

    yield db
    await db.close()


@pytest.mark.asyncio
async def test_combination_matrix_fcs_and_availability(combo_matrix_db):
    """
    ADVERSARIAL CHALLENGE 5: Verifies FCS and data availability behavior
    across all 4 combinations of ground sensor and active fire presence.
    """
    service = FacilityIntelligenceService(combo_matrix_db)

    # 1. Ground Only (Facility 301)
    ev_301 = await service.get_evidence_chain(301, radius_km=10.0)
    assert ev_301["data_availability"]["has_ground_stations"] is True
    assert ev_301["data_availability"]["has_fire_hotspots"] is False
    assert ev_301["ambient_quality"]["dominant_pollutant"] == "pm25"
    assert ev_301["ambient_quality"]["fcs"] > 0.0
    assert ev_301["thermal_correlation"]["state"] in ("NORMAL_CONDITIONS", "ELEVATED_PM_ONLY")

    # 2. Fires Only (Facility 302)
    ev_302 = await service.get_evidence_chain(302, radius_km=10.0)
    assert ev_302["data_availability"]["has_ground_stations"] is False
    assert ev_302["data_availability"]["has_fire_hotspots"] is True
    assert ev_302["ambient_quality"]["dominant_pollutant"] == "brightness"
    assert ev_302["ambient_quality"]["fcs"] > 0.0
    assert ev_302["thermal_correlation"]["state"] == "THERMAL_ANOMALY_ONLY"
    assert ev_302["thermal_correlation"]["fire_count"] == 1

    # 3. Both Ground and Fires (Facility 303)
    ev_303 = await service.get_evidence_chain(303, radius_km=10.0)
    assert ev_303["data_availability"]["has_ground_stations"] is True
    assert ev_303["data_availability"]["has_fire_hotspots"] is True
    assert ev_303["ambient_quality"]["dominant_pollutant"] == "pm25"
    assert ev_303["ambient_quality"]["fcs"] > 0.0
    assert ev_303["thermal_correlation"]["fire_count"] == 1
    assert ev_303["thermal_correlation"]["elevated_pm"] is True
    assert ev_303["thermal_correlation"]["state"] == "CONCURRENT_THERMAL_AND_PM_ANOMALY"

    # 4. Neither (Facility 304) -> Zero-Fake-Data
    ev_304 = await service.get_evidence_chain(304, radius_km=10.0)
    assert ev_304["data_availability"]["has_ground_stations"] is False
    assert ev_304["data_availability"]["has_fire_hotspots"] is False
    assert ev_304["data_availability"]["stations_count"] == 0
    assert ev_304["data_availability"]["fires_count"] == 0
    assert ev_304["ground_sensors"] == []
    assert ev_304["fire_events"] == []
    assert ev_304["ambient_quality"]["fcs"] == 0.0
    assert ev_304["ambient_quality"]["fcs_confidence"] == "INSUFFICIENT_DATA"
    assert ev_304["ambient_quality"]["dominant_pollutant"] is None
    assert ev_304["thermal_correlation"]["state"] == "DATA_UNAVAILABLE"
    assert ev_304["regulatory_summary"]["overall_status"] == "no_data"


# =============================================================================
# 5. Multi-Latitude Corner Trap & Antimeridian Adversarial Tests
# =============================================================================

@pytest.mark.asyncio
@pytest.mark.parametrize(
    "center_lat,center_lon,radius_km",
    [
        (0.0, 0.0, 10.0),        # Equator
        (0.0, 0.0, 25.0),        # Equator 25km
        (28.5, 77.2, 10.0),      # Subtropical (Delhi)
        (45.0, 10.0, 15.0),      # Mid-latitude
        (60.0, 25.0, 10.0),      # High-latitude (Helsinki)
        (75.0, 15.0, 10.0),      # Arctic
        (0.0, 179.95, 10.0),     # Dateline crossing (equator)
        (-18.0, 179.9, 20.0),    # Dateline crossing (Fiji region)
    ],
)
async def test_corner_trap_elimination_across_latitudes(center_lat, center_lon, radius_km):
    """
    ADVERSARIAL CHALLENGE 6: Multi-latitude corner trap elimination.
    Constructs bounding box corners across diverse latitudes and dateline crossings.
    Proves that for every case, corners inside the SQL bounding box (~1.414r)
    are strictly excluded by the spherical Haversine distance filter.
    """
    db = DatabaseManager()
    await db.initialize(":memory:")
    service = FacilityIntelligenceService(db)

    bbox = service.generate_bounding_box(center_lat, center_lon, radius_km)
    min_lat, max_lat = bbox["min_lat"], bbox["max_lat"]
    min_lon, max_lon = bbox["min_lon"], bbox["max_lon"]

    # Candidate corner points
    candidate_corners = [
        ("ne", max_lat, max_lon),
        ("nw", max_lat, min_lon),
        ("se", min_lat, max_lon),
        ("sw", min_lat, min_lon),
    ]

    now_iso = datetime.now(timezone.utc).isoformat()
    today_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    recent_acq_time = (datetime.now(timezone.utc) - timedelta(minutes=10)).strftime("%H%M")

    for prefix, c_lat, c_lon in candidate_corners:
        # Wrap longitude if needed
        norm_lon = (c_lon + 180.0) % 360.0 - 180.0
        st_id = f"st_corner_{prefix}"
        await db.execute(
            """INSERT INTO openaq_stations (station_id, name, latitude, longitude, city, country, last_updated, parameters)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?)""",
            (st_id, f"Corner {prefix}", c_lat, norm_lon, "Test", "XX", now_iso, "pm25"),
        )
        await db.execute(
            """INSERT INTO nasa_firms_fires (id, latitude, longitude, brightness, scan, track, acq_date, acq_time, satellite, confidence, frp, dqs)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
            (hash(prefix) % 10000 + 500, c_lat, norm_lon, 340.0, 1.0, 1.0, today_str, recent_acq_time, "VIIRS", "nominal", 10.0, 0.75),
        )

    # Query stations and fires
    found_stations = await service.get_openaq_stations_within_radius(center_lat, center_lon, radius_km)
    found_fires = await service.get_firms_fires_within_radius(center_lat, center_lon, radius_km)

    # ALL corners are at ~1.414 * radius_km > radius_km, hence ZERO should be returned
    for s in found_stations:
        assert s["distance_km"] <= radius_km, f"Station {s['station_id']} with dist {s['distance_km']} > {radius_km}"
    for f in found_fires:
        assert f["distance_km"] <= radius_km, f"Fire {f['id']} with dist {f['distance_km']} > {radius_km}"

    # Verify no corner traps slipped through
    assert len(found_stations) == 0, f"Corner trap stations survived at lat={center_lat}, lon={center_lon}!"
    assert len(found_fires) == 0, f"Corner trap fires survived at lat={center_lat}, lon={center_lon}!"

    await db.close()


# =============================================================================
# 6. Epsilon Tangent Boundary Precision (1 meter margin)
# =============================================================================

@pytest.mark.asyncio
async def test_tangent_epsilon_precision_1m():
    """
    ADVERSARIAL CHALLENGE 7: Epsilon precision at 1 meter margin.
    r = 10.0 km
    - Inner point at r - 1m = 9.999 km: MUST be included.
    - Exact point at r = 10.000 km: MUST be included.
    - Outer point at r + 1m = 10.001 km: MUST be excluded.
    """
    db = DatabaseManager()
    await db.initialize(":memory:")
    service = FacilityIntelligenceService(db)

    fac_lat, fac_lon = 28.5, 77.2
    radius_km = 10.0
    now_iso = datetime.now(timezone.utc).isoformat()

    # 1. Point at r - 1m (9.999 km) due north
    lat_inner, lon_inner = destination_point(fac_lat, fac_lon, distance_km=9.999, bearing_deg=0.0)
    await db.execute(
        """INSERT INTO openaq_stations (station_id, name, latitude, longitude, city, country, last_updated, parameters)
           VALUES (?, ?, ?, ?, ?, ?, ?, ?)""",
        ("st_inner_1m", "Inner 1m", lat_inner, lon_inner, "Delhi", "IN", now_iso, "pm25"),
    )

    # 2. Point at exact r (10.000 km) due north
    lat_exact, lon_exact = destination_point(fac_lat, fac_lon, distance_km=10.000, bearing_deg=0.0)
    await db.execute(
        """INSERT INTO openaq_stations (station_id, name, latitude, longitude, city, country, last_updated, parameters)
           VALUES (?, ?, ?, ?, ?, ?, ?, ?)""",
        ("st_exact_r", "Exact r", lat_exact, lon_exact, "Delhi", "IN", now_iso, "pm25"),
    )

    # 3. Point at r + 1m (10.001 km) due north
    lat_outer, lon_outer = destination_point(fac_lat, fac_lon, distance_km=10.001, bearing_deg=0.0)
    await db.execute(
        """INSERT INTO openaq_stations (station_id, name, latitude, longitude, city, country, last_updated, parameters)
           VALUES (?, ?, ?, ?, ?, ?, ?, ?)""",
        ("st_outer_1m", "Outer 1m", lat_outer, lon_outer, "Delhi", "IN", now_iso, "pm25"),
    )

    stations = await service.get_openaq_stations_within_radius(fac_lat, fac_lon, radius_km=radius_km)
    st_ids = {s["station_id"] for s in stations}

    assert "st_inner_1m" in st_ids, "Point at r - 1m must be included!"
    assert "st_exact_r" in st_ids, "Point at exact r must be included (d <= r)!"
    assert "st_outer_1m" not in st_ids, "Point at r + 1m must be strictly excluded (d > r)!"

    await db.close()


# =============================================================================
# 7. FCS Weighted Dispersion & Edge Cases
# =============================================================================

def test_fcs_weighted_dispersion_and_edge_cases():
    """
    ADVERSARIAL CHALLENGE 8: FCS source weights, unequal weighting, and extreme cases.
    """
    # Unequal weights: high weight on DQS=0.9, low weight on DQS=0.3
    # Values: [50.0, 50.0] (no dispersion, sigma = 0)
    # weighted DQS = (0.9 * 3.0 + 0.3 * 1.0) / 4.0 = 3.0 / 4.0 = 0.75
    fcs_weighted = calculate_fcs([0.9, 0.3], [50.0, 50.0], weights=[3.0, 1.0])
    assert fcs_weighted == pytest.approx(0.750000, abs=1e-4)

    # Negative and zero weights handled cleanly
    # Weight of 0 should be ignored in weighted DQS
    fcs_zero_weight = calculate_fcs([0.9, 0.3], [50.0, 50.0], weights=[1.0, 0.0])
    assert fcs_zero_weight == pytest.approx(0.900000, abs=1e-4)

    # All weights zero -> returns 0.0
    assert calculate_fcs([0.9, 0.8], [50.0, 50.0], weights=[0.0, 0.0]) == 0.0

    # Negative weight clamped or treated as 0.0
    fcs_neg_weight = calculate_fcs([0.9, 0.3], [50.0, 50.0], weights=[1.0, -1.0])
    assert fcs_neg_weight == pytest.approx(0.900000, abs=1e-4)

